version: "3.8"
services:
  api:
    container_name: api
    build:
      context: .
    environment:
      - DB_HOST=psql
      - POSTGRES_DB=docks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_ROOT_PASSWORD=123
    depends_on:
      - psql
    ports:
      - 8080:8080
    networks:
      - api-network
  psql:
    hostname: "psql"
    image: postgres:latest
    container_name: psql
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=docks
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_ROOT_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/psql/data
    networks:
      - api-network
volumes:
  db:
networks:
  api-network:
